import { Item } from 'src/types/item';
import {
	PageHomeComponent,
	PageAboutComponent,
	PageNotFoundComponent,
	PageDesignProbesComponent,
	PageHumanCenteredDesignComponent,
	PageCriticalDesignComponent,
	PagePersonalManifestoComponent,
	PageStoryCreationComponent,
	PagePechaKuchaComponent,
	PageMediaTheoryComponent,
	PageOtherComponent,
	PageVegaCollabComponent,
	PageCriticalProblemsComponent,
	PageConceptsComponent,
	PageConceptDigitalDetoxComponent,
	PagePrintHouseInterviewComponent,
	PageResearchStorytellingEmotionComponent,
	PageADayWithoutMyPhoneComponent,
	PageSocialAnalysisComponent,
	PageMyAIFriendComponent,
	PageGroupContributionComponent,
	PageStakeholderProfilesComponent,
	PageProtaganistComponent,
} from 'src/app/pages';

const items: Item[] = [
	{
		id: 1,
		path: '',
		component: PageHomeComponent,
		title: 'Home',
		emoji: '🏠',
		redirects: ['home', 'thuis'],
		children: [],
		includeInRoutes: true,
		includeInNavigation: true,
	},
	{
		id: 2,
		path: 'about',
		component: PageAboutComponent,
		title: 'About',
		icon: '🤖',
		redirects: ['me', 'ik', 'over'],
		children: [],
		includeInRoutes: true,
		includeInNavigation: true,
	},
	{
		id: 100,
		path: 'human-centered-design',
		component: PageHumanCenteredDesignComponent,
		title: 'Human Centered Design',
		redirects: ['hcd'],
		includeInRoutes: true,
		includeInNavigation: true,
		children: [
			{
				id: 101,
				path: 'design-probes',
				component: PageDesignProbesComponent,
				title: 'Design probes',
				emoji: '⚗️',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 102,
				path: 'print-house-interview',
				component: PagePrintHouseInterviewComponent,
				title: '2D print house interview',
				emoji: '🏭',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 103,
				path: 'stakeholder-profiles',
				component: PageStakeholderProfilesComponent,
				title: 'Stakeholder Profiles',
				emoji: '🧝‍♂️',
				includeInRoutes: true,
				includeInNavigation: true,
			},
		],
	},
	{
		id: 200,
		path: 'critical-design',
		component: PageCriticalDesignComponent,
		title: 'Critical Design',
		redirects: ['cd'],
		includeInRoutes: true,
		includeInNavigation: true,
		children: [
			{
				id: 201,
				path: 'critical-problems',
				component: PageCriticalProblemsComponent,
				title: 'Critical problems',
				emoji: '⚠️',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 202,
				path: 'personal-manifesto',
				component: PagePersonalManifestoComponent,
				title: 'Personal Manifesto',
				emoji: '💁‍♂️',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 203,
				path: 'concepts',
				component: PageConceptsComponent,
				title: 'Concepts',
				emoji: '💡',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 204,
				path: 'concept-digital-detox',
				component: PageConceptDigitalDetoxComponent,
				title: 'Concept: Digital Detox',
				emoji: '🌌',
				includeInRoutes: true,
				includeInNavigation: true,
			},
		],
	},
	{
		id: 300,
		path: 'story-creation',
		component: PageStoryCreationComponent,
		title: 'Story Creation',
		redirects: ['sc'],
		includeInRoutes: true,
		includeInNavigation: true,
		children: [
			{
				id: 301,
				path: 'pecha-kucha',
				component: PagePechaKuchaComponent,
				title: 'Pecha Kucha',
				icon: '⏰',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 302,
				path: 'research-storytelling-emotion',
				component: PageResearchStorytellingEmotionComponent,
				title: 'Research Storytelling & Emotion',
				emoji: '📝',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 303,
				path: 'protaganist',
				component: PageProtaganistComponent,
				title: 'Protaganist',
				emoji: '🚶',
				includeInRoutes: true,
				includeInNavigation: true,
			},
		],
	},
	{
		id: 400,
		path: 'media-theory',
		component: PageMediaTheoryComponent,
		title: 'Media Theory',
		redirects: ['mt'],
		includeInRoutes: true,
		includeInNavigation: true,
		children: [
			{
				id: 401,
				path: 'a-day-without-my-phone',
				component: PageADayWithoutMyPhoneComponent,
				title: 'A day without my phone',
				emoji: '📴',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 402,
				path: 'social-analysis',
				component: PageSocialAnalysisComponent,
				title: 'Social Analysis',
				emoji: '🗣',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 403,
				path: 'my-ai-friend',
				component: PageMyAIFriendComponent,
				title: 'My AI friend',
				emoji: '🦾',
				includeInRoutes: true,
				includeInNavigation: true,
			},
		],
	},
	{
		id: 500,
		path: 'other',
		component: PageOtherComponent,
		title: 'Other',
		includeInRoutes: true,
		includeInNavigation: true,
		children: [
			{
				id: 501,
				path: 'vega-collab',
				component: PageVegaCollabComponent,
				title: 'VEGA Collab',
				emoji: '🇿🇦',
				includeInRoutes: true,
				includeInNavigation: true,
			},
			{
				id: 502,
				path: 'group-contribution',
				component: PageGroupContributionComponent,
				title: 'Group Contribution',
				emoji: '👥',
				includeInRoutes: true,
				includeInNavigation: true,
			},
		],
	},
	{
		id: 0,
		path: '**',
		component: PageNotFoundComponent,
		title: 'Not found',
		emoji: 'person',
		redirects: ['404', 'not-found', 'niet-gevonden'],
		children: [],
		includeInRoutes: true,
		includeInNavigation: false,
	},
];

export default {
	title: 'Portfolio S7 – Max Altena',
	items,
};
